[package]
name = "dark-notify"
version = "0.1.2"
authors = ["Cormac Relf <web@cormacrelf.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cocoa = "0.24.0"
objc = "0.2.7"
anyhow = "1.0.65"
bitflags = "1.3.2"
libc = "0.2.134"
lazy_static = "1.4.0"
structopt = "0.3.26"
